"""Initial schema

Revision ID: a33b8a66fd24
Revises: 
Create Date: 2026-01-14 10:06:07.603077

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a33b8a66fd24'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False, comment='病例ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='病例标题'),
    sa.Column('difficulty', sa.String(length=20), nullable=False, comment='难度：easy/medium/hard'),
    sa.Column('department', sa.String(length=50), nullable=False, comment='科室'),
    sa.Column('patient_info', sa.JSON(), nullable=False, comment='患者基本信息（年龄、性别、职业等）'),
    sa.Column('chief_complaint', sa.Text(), nullable=False, comment='主诉'),
    sa.Column('present_illness', sa.Text(), nullable=False, comment='现病史'),
    sa.Column('past_history', sa.JSON(), nullable=False, comment='既往史（疾病、过敏、用药等）'),
    sa.Column('physical_exam', sa.JSON(), nullable=False, comment='体格检查（可见体征和按需提供的体征）'),
    sa.Column('available_tests', sa.JSON(), nullable=False, comment='可申请的检查项及结果'),
    sa.Column('standard_diagnosis', sa.JSON(), nullable=False, comment='标准诊断（主要诊断、鉴别诊断）'),
    sa.Column('key_points', sa.JSON(), nullable=False, comment='关键问诊点列表'),
    sa.Column('recommended_tests', sa.JSON(), nullable=True, comment='推荐检查项列表'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cases'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('full_name', sa.String(length=100), nullable=False, comment='姓名'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='角色：student/teacher/admin'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活'),
    sa.Column('external_user_id', sa.String(length=100), nullable=True, comment='外部系统用户ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_external_user_id'), 'users', ['external_user_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False, comment='日志ID'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户ID'),
    sa.Column('action', sa.String(length=50), nullable=False, comment='操作类型（如：login、chat、submit、score）'),
    sa.Column('resource_type', sa.String(length=50), nullable=True, comment='资源类型（如：session、case）'),
    sa.Column('resource_id', sa.String(length=100), nullable=True, comment='资源ID'),
    sa.Column('details', sa.JSON(), nullable=True, comment='操作详情（JSON 格式）'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IP 地址'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='User Agent'),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False, comment='会话ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('case_id', sa.Integer(), nullable=False, comment='病例ID'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态：in_progress/submitted/scored'),
    sa.Column('submitted_diagnosis', sa.Text(), nullable=True, comment='学生提交的诊断结论'),
    sa.Column('started_at', sa.DateTime(), server_default='now()', nullable=False, comment='开始时间'),
    sa.Column('ended_at', sa.DateTime(), nullable=True, comment='结束时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_sessions_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_index(op.f('ix_sessions_case_id'), 'sessions', ['case_id'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False, comment='消息ID'),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='会话ID'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='角色：user/assistant'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('tokens', sa.Integer(), nullable=True, comment='token 数量'),
    sa.Column('latency_ms', sa.Integer(), nullable=True, comment='响应延迟（毫秒）'),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_messages_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False, comment='评分ID'),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='会话ID（唯一）'),
    sa.Column('total_score', sa.Numeric(precision=5, scale=2), nullable=False, comment='总分（0-100）'),
    sa.Column('dimensions', sa.JSON(), nullable=False, comment='各维度得分（问诊完整性、检查合理性、诊断准确性等）'),
    sa.Column('scoring_details', sa.JSON(), nullable=False, comment='评分详情（关键词覆盖、推荐检查匹配等）'),
    sa.Column('scoring_method', sa.String(), nullable=False, comment='评分方式：rule_based/llm_based'),
    sa.Column('model_version', sa.String(), nullable=True, comment='使用的模型版本（如适用）'),
    sa.Column('scored_at', sa.DateTime(), server_default='now()', nullable=False, comment='评分时间'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_scores_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scores'))
    )
    op.create_index(op.f('ix_scores_session_id'), 'scores', ['session_id'], unique=True)
    op.create_table('test_requests',
    sa.Column('id', sa.Integer(), nullable=False, comment='检查申请ID'),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='会话ID'),
    sa.Column('test_type', sa.String(length=50), nullable=False, comment='检查类型（如：blood_routine、x_ray）'),
    sa.Column('test_name', sa.String(length=100), nullable=False, comment='检查名称'),
    sa.Column('result', sa.JSON(), nullable=False, comment='检查结果（JSON 格式）'),
    sa.Column('requested_at', sa.DateTime(), server_default='now()', nullable=False, comment='申请时间'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_test_requests_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_test_requests'))
    )
    op.create_index(op.f('ix_test_requests_session_id'), 'test_requests', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_requests_session_id'), table_name='test_requests')
    op.drop_table('test_requests')
    op.drop_index(op.f('ix_scores_session_id'), table_name='scores')
    op.drop_table('scores')
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_case_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_external_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('cases')
    # ### end Alembic commands ###
